### ISSUE TITLE
Installation of Home Assistant

### ISSUE THREAD

**Issue by gbraad** [gbraad-homelab/personal-homeassistant#1]
- https://fedoraproject.org/wiki/Home_Assistant#Installing_core_type

### Network

The following is needed
`~hass/.homeassistant/configuration.yaml`
```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - [systemip]
```
to allow Cloudflare and Tailscale to work.

### Storage

- https://www.home-assistant.io/more-info/local-media/setup-media
